version: "3"
services:
  # サイトサーバは変更しない
  # web:
  #   build:
  #     context: ./docker/site
  #     dockerfile: Dockerfile
  #   image: goropikari/dmoj-site:dev

  judger:
    build:
      context: ./docker/judger
      dockerfile: Dockerfile
    image: goropikari/dmoj-judger:dev
